name: 构建VSCode插件

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 安装vsce
      run: npm install -g @vscode/vsce
      
    - name: 安装rimraf
      run: npm install --save-dev rimraf
      
    - name: 构建插件
      run: |
        npm run compile
        npx rimraf out
        npx webpack --mode production
      
    - name: 打包VSIX
      run: vsce package
      
    - name: 获取包名和版本
      id: package-info
      run: |
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
      
    - name: 上传VSIX构建产物
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.package-info.outputs.name }}-${{ steps.package-info.outputs.version }}
        path: ${{ steps.package-info.outputs.name }}-${{ steps.package-info.outputs.version }}.vsix
        retention-days: 30
